<tt>
Hello,&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;am&nbsp;working&nbsp;an&nbsp;a&nbsp;Python&nbsp;program&nbsp;that&nbsp;receives&nbsp;XML-RPC&nbsp;calls&nbsp;from&nbsp;Java&nbsp;clients,&nbsp;and&nbsp;then&nbsp;create&nbsp;AMQP&nbsp;queues&nbsp;for&nbsp;each&nbsp;client.&lt;/div&gt;&lt;div&gt;To&nbsp;create&nbsp;channel,&nbsp;exchanges&nbsp;and&nbsp;queues,&nbsp;we&nbsp;use&nbsp;pika&nbsp;and&nbsp;SelectConnection.&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;So&nbsp;I&nbsp;first&nbsp;create&nbsp;and&nbsp;start&nbsp;a&nbsp;SelectConnection,&nbsp;then&nbsp;I&nbsp;create&nbsp;a&nbsp;channel.&nbsp;On&nbsp;the&nbsp;reception&nbsp;of&nbsp;the&nbsp;on_open_callback&nbsp;of&nbsp;the&nbsp;channel,&nbsp;I&nbsp;try&nbsp;to&nbsp;declare&nbsp;a&nbsp;queue.&lt;/div&gt;&lt;div&gt;The&nbsp;problem&nbsp;is&nbsp;that&nbsp;about&nbsp;10%&nbsp;of&nbsp;time, a weird&nbsp;error&nbsp;occurs&nbsp;on&nbsp;the&nbsp;declaration&nbsp;of&nbsp;the&nbsp;queue&nbsp;:&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;File&nbsp;&amp;quot;/usr/lib/python2.6/multiprocessing/process.py&amp;quot;,&nbsp;line&nbsp;232,&nbsp;in&nbsp;_bootstrap&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;self.run()&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/usr/lib/python2.6/multiprocessing/process.py&amp;quot;,&nbsp;line&nbsp;88,&nbsp;in&nbsp;run&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp;self._target(*self._args,&nbsp;**self._kwargs)&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/Sources/svn/TOTEM/Sandbox/TSP-MARGE-Communication/RabbitMQ/RabbitMQTOTEMLibrary/Python/net/totem/gamelogic/creategamelogicserver.py&amp;quot;,&nbsp;line&nbsp;42,&nbsp;in&nbsp;createGameLogicServer&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp;state.connection.ioloop.start()&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/adapters/select_connection.py&amp;quot;,&nbsp;line&nbsp;124,&nbsp;in&nbsp;start&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;self.poller.start()&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/adapters/select_connection.py&amp;quot;,&nbsp;line&nbsp;374,&nbsp;in&nbsp;start&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp;self.poll()&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/adapters/select_connection.py&amp;quot;,&nbsp;line&nbsp;388,&nbsp;in&nbsp;poll&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;self._handler(events[0][0],&nbsp;events[0][1])&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/adapters/base_connection.py&amp;quot;,&nbsp;line&nbsp;134,&nbsp;in&nbsp;_handle_events&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp;self._handle_read()&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/adapters/base_connection.py&amp;quot;,&nbsp;line&nbsp;162,&nbsp;in&nbsp;_handle_read&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;self._on_data_available(data)&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/connection.py&amp;quot;,&nbsp;line&nbsp;599,&nbsp;in&nbsp;_on_data_available&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp;self._channels[frame.channel_number].transport.deliver(frame)&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/channel.py&amp;quot;,&nbsp;line&nbsp;64,&nbsp;in&nbsp;deliver&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;self.frame_dispatcher.process(frame)&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/frame.py&amp;quot;,&nbsp;line&nbsp;202,&nbsp;in&nbsp;process&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;self._handler(frame)&lt;/div&gt;&lt;div&gt; &nbsp;File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/frame.py&amp;quot;,&nbsp;line&nbsp;220,&nbsp;in&nbsp;_handle_method_frame&lt;/div&gt;<br>
<br>
&lt;div&gt; &nbsp; &nbsp;raise&nbsp;NotImplementedError(frame.method.__class__)&lt;/div&gt;&lt;div&gt;NotImplementedError:&nbsp;&amp;lt;class&nbsp;&amp;#39;pika.spec.DeclareOk&amp;#39;&amp;gt;&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;We&nbsp;have&nbsp;already&nbsp;sent&nbsp;you&nbsp;a&nbsp;mail&nbsp;6&nbsp;months&nbsp;ago,&nbsp;and&nbsp;someone&nbsp;tell&nbsp;us&nbsp;to&nbsp;change&nbsp;the&nbsp;pika&nbsp;source&nbsp;code&nbsp;to&nbsp;have&nbsp;a&nbsp;better&nbsp;understanding&nbsp;of&nbsp;this&nbsp;error,&nbsp;and&nbsp;here&nbsp;is&nbsp;the&nbsp;result&nbsp;:&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;div&gt; File&nbsp;&amp;quot;/home/adgeg/local/bin/pika-0.9.5/pika/frame.py&amp;quot;,&nbsp;line&nbsp;220,&nbsp;in&nbsp;_handle_method_frame&lt;/div&gt;&lt;div&gt; &nbsp; &nbsp;raise&nbsp;NotImplementedError(frame.method.__class__)&lt;/div&gt;&lt;/div&gt;&lt;div&gt;NotImplementedError:&nbsp;&amp;lt;Method([&amp;#39;frame_type=1&amp;#39;,&nbsp;&amp;#39;channel_number=1&amp;#39;,&nbsp;&amp;quot;method=&amp;lt;Queue.DeclareOk([&amp;#39;queue=michel&amp;#39;,&nbsp;&amp;#39;message_count=0&amp;#39;,&nbsp;&amp;#39;consumer_count=0&amp;#39;])&amp;gt;&amp;quot;])&amp;gt;&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;have&nbsp;looked&nbsp;to&nbsp;our&nbsp;source&nbsp;code,&nbsp;and&nbsp;I&nbsp;found&nbsp;that&nbsp;we&nbsp;were&nbsp;using&nbsp;the&nbsp;same&nbsp;channel&nbsp;in&nbsp;two&nbsp;different&nbsp;threads.&lt;/div&gt;&lt;div&gt;So&nbsp;I&nbsp;create&nbsp;a&nbsp;new&nbsp;channel&nbsp;(with&nbsp;its&nbsp;own&nbsp;SelectConnection)&nbsp;for&nbsp;the&nbsp;second&nbsp;thread...&nbsp;but&nbsp;the&nbsp;error&nbsp;is&nbsp;still&nbsp;raised.&lt;/div&gt;<br>
<br>
&lt;div&gt;Curiously,&nbsp;I&nbsp;have&nbsp;found&nbsp;a&nbsp;way&nbsp;to&nbsp;highly&nbsp;reduce&nbsp;appearance&nbsp;frequency&nbsp;of&nbsp;the&nbsp;error:&nbsp;I&nbsp;accidentally&nbsp;add&nbsp;a&nbsp;call&nbsp;to&nbsp;a&nbsp;system&nbsp;command&nbsp;on&nbsp;the&nbsp;Python&nbsp;source&nbsp;code&nbsp;on&nbsp;the on_open_callback,&nbsp;just&nbsp;before&nbsp;declaring&nbsp;the&nbsp;queue (rabbitmqctl&nbsp;list_user_permissions,&nbsp;to&nbsp;check&nbsp;that&nbsp;I&nbsp;have&nbsp;the&nbsp;required&nbsp;permissions&nbsp;to&nbsp;declare&nbsp;a&nbsp;queue).&lt;/div&gt;<br>
<br>
&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;And&nbsp;now,&nbsp;it&nbsp;seems&nbsp;that&nbsp;we&nbsp;arrived&nbsp;to&nbsp;an appearance&nbsp;frequency&nbsp;of&nbsp;3&nbsp;times&nbsp;on&nbsp;2000&nbsp;tries.&lt;/div&gt;&lt;div&gt;So&nbsp;I&nbsp;suppose&nbsp;that&nbsp;without&nbsp;this&nbsp;additional&nbsp;little&nbsp;time&nbsp;period,&nbsp;the on_open_callback&nbsp;is&nbsp;triggered,&nbsp;but&nbsp;the&nbsp;channel&nbsp;seems&nbsp;not&nbsp;able&nbsp;to&nbsp;declare&nbsp;a&nbsp;queue.&lt;/div&gt;<br>
<br>
&lt;div&gt;Do&nbsp;you&nbsp;know&nbsp;some&nbsp;related&nbsp;issues&nbsp;of&nbsp;this&nbsp;kind&nbsp;on&nbsp;SelectConnections?&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Thanks&nbsp;a&nbsp;lot,&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Gabriel&nbsp;Adgeg&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;PS&nbsp;:&nbsp;I&nbsp;am&nbsp;using&nbsp;RabbitMQ&nbsp;2.7.0,&nbsp;Erlang&nbsp;R13B03,&nbsp;Python&nbsp;2.6.5,&nbsp;pika&nbsp;0.9.5,&nbsp;on Ubuntu&nbsp;10.04.3&nbsp;LTS.&nbsp;The&nbsp;error&nbsp;also&nbsp;occurs&nbsp;with&nbsp;Erlang&nbsp;R14B04,&nbsp;Python&nbsp;2.7.2,&nbsp;on&nbsp;Windows&nbsp;XP&nbsp;and&nbsp;Windows&nbsp;7.&nbsp;And&nbsp;it&nbsp;was&nbsp;already&nbsp;there&nbsp;when&nbsp;we&nbsp;were&nbsp;using&nbsp;RabbitMQ&nbsp;2.5.1. &lt;/div&gt;<br>
<br>

</tt>
