<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] AMQPChannelException: (404,	u&quot;NOT_FOUND - no exchange '4042acd4bbec471aafc557af39ee0efe' in	vhost '/'&quot;, (60, 40), 'Channel.basic_publish')
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20AMQPChannelException%3A%20%28404%2C%0A%09u%22NOT_FOUND%20-%20no%20exchange%20%274042acd4bbec471aafc557af39ee0efe%27%20in%0A%09vhost%20%27/%27%22%2C%20%2860%2C%2040%29%2C%20%27Channel.basic_publish%27%29&In-Reply-To=%3C0332A3E1-A471-49C2-AD7D-0E471E95CA59%40rabbitmq.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="024568.html">
   <LINK REL="Next"  HREF="024583.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] AMQPChannelException: (404,	u&quot;NOT_FOUND - no exchange '4042acd4bbec471aafc557af39ee0efe' in	vhost '/'&quot;, (60, 40), 'Channel.basic_publish')</H1>
    <B>Ask Solem</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20AMQPChannelException%3A%20%28404%2C%0A%09u%22NOT_FOUND%20-%20no%20exchange%20%274042acd4bbec471aafc557af39ee0efe%27%20in%0A%09vhost%20%27/%27%22%2C%20%2860%2C%2040%29%2C%20%27Channel.basic_publish%27%29&In-Reply-To=%3C0332A3E1-A471-49C2-AD7D-0E471E95CA59%40rabbitmq.com%3E"
       TITLE="[rabbitmq-discuss] AMQPChannelException: (404,	u&quot;NOT_FOUND - no exchange '4042acd4bbec471aafc557af39ee0efe' in	vhost '/'&quot;, (60, 40), 'Channel.basic_publish')">ask at rabbitmq.com
       </A><BR>
    <I>Wed Dec 19 16:48:47 GMT 2012</I>
    <P><UL>
        <LI>Previous message: <A HREF="024568.html">[rabbitmq-discuss] AMQPChannelException: (404,	u&quot;NOT_FOUND - no exchange '4042acd4bbec471aafc557af39ee0efe' in	vhost '/'&quot;, (60, 40), 'Channel.basic_publish')
</A></li>
        <LI>Next message: <A HREF="024583.html">[rabbitmq-discuss] Distributing Tasks to Worker Queues Across	Federated Exchanges
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#24599">[ date ]</a>
              <a href="thread.html#24599">[ thread ]</a>
              <a href="subject.html#24599">[ subject ]</a>
              <a href="author.html#24599">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
On 18 Dec 2012, at 08:54, Alex Lyakas &lt;<A HREF="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">alex at zadarastorage.com</A>&gt; wrote:

&gt;<i> Greetings all,
</I>&gt;<i> 
</I>&gt;<i> I am using rabbitmq server + kombu + pyamqplib on a stock Ubuntu-Precise. Below are the versions of the components:
</I>&gt;<i> rabbitmq-server 2.7.1-0ubuntu4
</I>&gt;<i> python-amqplib  1.0.0+ds-1
</I>&gt;<i> python-kombu 1.4.3-1
</I>&gt;<i> 
</I>&gt;<i> The issue I am seeing is the &#8220;no exchange&#8221; exception, which I hit when opening a new channel on an existing connection. Here is a typical crash stack:
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/kombu/connection.py&quot;, line 159, in channel
</I>&gt;<i> TRACE: chan = self.transport.create_channel(self.connection)
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/kombu/transport/pyamqplib.py&quot;, line 235, in create_channel
</I>&gt;<i> TRACE: return connection.channel()
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/kombu/transport/pyamqplib.py&quot;, line 144, in channel
</I>&gt;<i> TRACE: return Channel(self, channel_id)
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/kombu/transport/pyamqplib.py&quot;, line 183, in init
</I>&gt;<i> TRACE: super(Channel, self).__init__(*args, **kwargs)
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/channel.py&quot;, line 82, in init
</I>&gt;<i> TRACE: self._x_open()
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/channel.py&quot;, line 471, in _x_open
</I>&gt;<i> TRACE: (20, 11), # Channel.open_ok
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/abstract_channel.py&quot;, line 97, in wait
</I>&gt;<i> TRACE: return self.dispatch_method(method_sig, args, content)
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/abstract_channel.py&quot;, line 115, in dispatch_method
</I>&gt;<i> TRACE: return amqp_method(self, args)
</I>&gt;<i> TRACE: File &quot;/usr/lib/python2.7/dist-packages/amqplib/client_0_8/channel.py&quot;, line 273, in _close
</I>&gt;<i> TRACE: (class_id, method_id))
</I>&gt;<i> TRACE: AMQPChannelException: (404, u&quot;NOT_FOUND - no exchange '4042acd4bbec471aafc557af39ee0efe' in vhost '/'&quot;, (60, 40), 'Channel.basic_publish')
</I>&gt;<i> 
</I>&gt;<i> I hit this only with direct exchanges, with &#8220;auto-delete&#8221; = True.
</I>&gt;<i> 
</I>&gt;<i> The flow that I have is like follows:
</I>&gt;<i> - node A declares a direct exchange and declares a queue
</I>&gt;<i> - node A sends message to node B using a topic exchange, and embeds direct exchange name in the message
</I>&gt;<i> - node B parses the message, prepares the reply, declares the (same) direct exchange and a producer
</I>&gt;<i> - node B sends reply message on the producer
</I>&gt;<i> - node A and node B close their channels
</I>&gt;<i> - several seconds after that, when node B tries to create a new channel on the same connection (using the same channel_id), it hits this exception.
</I>&gt;<i> 
</I>&gt;<i> I am trying to debug this for some time, but do not have a clear way to repro this. It happens occasionally.
</I>&gt;<i> 
</I>&gt;<i> I understand, that since I open the channel with the same channel_id, I may receive some stale message from the server (for the same channel_id) regarding failure to publish. However, several things confuse me:
</I>&gt;<i> 
</I>&gt;<i> 1) The only code, which publishes to a direct exchange is as follows:
</I>&gt;<i> self.exchange = kombu.entity.Exchange(name=self.exchange_name, **self.kwargs)
</I>&gt;<i> self.producer = kombu.messaging.Producer(exchange=self.exchange, channel=channel, routing_key=self.routing_key)
</I>&gt;<i> self.producer.publish(msg)
</I>&gt;<i> How can exchange not being present here?
</I>
The Kombu producer object will declare the exchange at construction.

This is the default behavior, but it's no longer a best practice to use it.  Sadly documentation is scarce
as I have not had as much time as I'd like to update it.

The best way to use a Producer object in Kombu is to instantiate it without a default exchange,
and rather use the exchange argument to publish:

    prod = Producer(connection)
    prod.publish(message,
                            exchange=exchange,
                            routing_key=routing_key,
                            declare=[exchange],
                     )


The declare argument takes a list of entities (Queue's / Exchange's) that must declared before
publishing the message, and these are cached if possible (state belonging to the current connection, so that
they will be redeclared if the connection is lost)

Using the Producer like this also enables you to use the retry argument properly so that the declare operation
also happens before a retry:

    prod.publish(message,
                            exchange=exchange,
                            declare=[exchange],
                            retry=True,
                            retry_policy={
                                'max_retries': None,
                                'interval_start': 2.0,
                                'interval_step': 2.0,
                                'interval_max': 30.0,
                            })

The retry_policy argument can be a dict containing any of the arguments supported
by Connection.ensure_connection:

<A HREF="http://kombu.readthedocs.org/en/latest/reference/kombu.html#kombu.Connection.ensure_connection">http://kombu.readthedocs.org/en/latest/reference/kombu.html#kombu.Connection.ensure_connection</A>

&gt;<i> 
</I>&gt;<i> 2) Even though all exchanges have auto-delete=True, I see more than 3000 existing direct exchanges on the rabbitmqctl list_exchanges output. The queues that used these exchanges (also auto-delete=True) do not exist anymore.
</I>&gt;<i> When auto-delete=True exchanges are deleted? Is there some timeout on their deletion? The documentation says that there SHOULD be a reasonable timeout. What is this timeout? Can it be configured? Is exchange auto-deletion supposed to work in my version?
</I>
I'm unsure of the exact details but it has probably been mentioned before if you search the mailing-list archives.
You are not recommended to use the auto_delete flag anymore, and in fact it's no longer supported by
some clients (i.e. librabbitmq)

&gt;<i> 
</I>&gt;<i> 3) The exchanges that I receive exceptions about do not exist indeed. How can I debug the rabbitmq server and understand why it decides to delete some exchanges, but not the other ones?
</I>
</PRE>




















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="024568.html">[rabbitmq-discuss] AMQPChannelException: (404,	u&quot;NOT_FOUND - no exchange '4042acd4bbec471aafc557af39ee0efe' in	vhost '/'&quot;, (60, 40), 'Channel.basic_publish')
</A></li>
	<LI>Next message: <A HREF="024583.html">[rabbitmq-discuss] Distributing Tasks to Worker Queues Across	Federated Exchanges
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#24599">[ date ]</a>
              <a href="thread.html#24599">[ thread ]</a>
              <a href="subject.html#24599">[ subject ]</a>
              <a href="author.html#24599">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
