<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Socket%20Error%20104%20when%20connecting%20to%20rabbit%0A%09cluster&In-Reply-To=%3CCA%2BBFTFsT1b7gRypVDDOsqryWkKyOMOGenoEc460ugNZK6CP_Pw%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="028526.html">
   <LINK REL="Next"  HREF="028529.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster</H1>
    <B>Rubo Liang</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Socket%20Error%20104%20when%20connecting%20to%20rabbit%0A%09cluster&In-Reply-To=%3CCA%2BBFTFsT1b7gRypVDDOsqryWkKyOMOGenoEc460ugNZK6CP_Pw%40mail.gmail.com%3E"
       TITLE="[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster">liangrubo at bytedance.com
       </A><BR>
    <I>Fri Jul 12 08:19:47 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="028526.html">[rabbitmq-discuss] Changing Durability of the queue.
</A></li>
        <LI>Next message: <A HREF="028529.html">[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#28521">[ date ]</a>
              <a href="thread.html#28521">[ thread ]</a>
              <a href="subject.html#28521">[ subject ]</a>
              <a href="author.html#28521">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

I have a rabbit cluster with 3 servers. I got error message like following
when trying to connect to it (the cluster has worked well for 2 days):

Socket Error on fd 3: 104

Details:

The cluster has 3 servers: A, B, C. Clients connect to server A. I run
'rabbitmqctl
stop_app; rabbitmqctl reset; rabbitmqctl start_app' on Server A to bring
the service back. Then I try to connect to server B but get the same error.

I can telnet rabbit port on server B.

~$ rabbitmqctl list_queues
Listing queues ...
ha.snssdk.log   0
ha.snssdk.log.dispatch  0
ha.snssdk.log.output    0
...done.

'rabbitmqctl report' output:

<A HREF="https://gist.github.com/liangrubo/5982515">https://gist.github.com/liangrubo/5982515</A>

pika stacktrace:
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;,
line 61, in __init__
    super(BaseConnection, self).__init__(parameters, on_open_callback)
  File &quot;/usr/local/lib/python2.7/dist-packages/pika/connection.py&quot;, line
513, in __init__
    self._connect()
  File &quot;/usr/local/lib/python2.7/dist-packages/pika/connection.py&quot;, line
804, in _connect
    self._adapter_connect()
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
line 146, in _adapter_connect
    self.process_data_events()
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
line 88, in process_data_events
    if self._handle_read():
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
line 184, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;,
line 300, in _handle_read
    return self._handle_error(error)
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;,
line 264, in _handle_error
    self._handle_disconnect()
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
line 181, in _handle_disconnect
    self._on_connection_closed(None, True)
  File
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;,
line 235, in _on_connection_closed
    raise exceptions.AMQPConnectionError(*self.closing)
pika.exceptions.AMQPConnectionError: (0, '')

Any help is appreciated.

Thanks.
Robert
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130712/d5a20e90/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130712/d5a20e90/attachment.htm</A>&gt;
</PRE>


































































<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="028526.html">[rabbitmq-discuss] Changing Durability of the queue.
</A></li>
	<LI>Next message: <A HREF="028529.html">[rabbitmq-discuss] Socket Error 104 when connecting to rabbit	cluster
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#28521">[ date ]</a>
              <a href="thread.html#28521">[ thread ]</a>
              <a href="subject.html#28521">[ subject ]</a>
              <a href="author.html#28521">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
