<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%20pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3Cd27a4c63-f9b0-4796-8482-00015d951da3%40googlegroups.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="030227.html">
   <LINK REL="Next"  HREF="030184.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError</H1>
    <B>&#38816;&#22823;&#21319;</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%20pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3Cd27a4c63-f9b0-4796-8482-00015d951da3%40googlegroups.com%3E"
       TITLE="[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError">dashengju at gmail.com
       </A><BR>
    <I>Mon Sep 16 16:04:35 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="030227.html">[rabbitmq-discuss] Mobile Client Request [	iOS/Android/HTML5/etc...]
</A></li>
        <LI>Next message: <A HREF="030184.html">[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30183">[ date ]</a>
              <a href="thread.html#30183">[ thread ]</a>
              <a href="subject.html#30183">[ subject ]</a>
              <a href="author.html#30183">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>hi, all

I am newer to rabbitmq.

I install a rabbitmq, just download, setup and startup the server. then I 
use a simple python client to connect, but the client report a error.

=================================================
Here is my version config:
python: 2.7
rabbitmq:  rabbitmq-server-generic-unix-3.1.5.tar.gz
erlang: otp_src_R16B01
pika: master

=================================================
Here is my python client:
#!/usr/bin/env python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(
            host='localhost'))
channel = connection.channel()


channel.queue_declare(queue='hello')

channel.basic_publish(exchange='',
            routing_key='hello',
            body='Hello World!')
print &quot; [x] Sent 'Hello World!'&quot;
connection.close()

=================================================
Here is the error info:
Traceback (most recent call last):
  File &quot;send.py&quot;, line 5, in &lt;module&gt;
    host='localhost'))
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 123, in __init__
    super(BlockingConnection, self).__init__(parameters, None, False)
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
line 62, in __init__
    on_close_callback)
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/connection.py&quot;, 
line 593, in __init__
    self.connect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 223, in connect
    error = self._adapter_connect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 302, in _adapter_connect
    self.process_data_events()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 233, in process_data_events
    if self._handle_read():
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 346, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
line 323, in _handle_read
    return self._handle_error(error)
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
line 287, in _handle_error
    self._handle_disconnect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 336, in _handle_disconnect
    self._adapter_disconnect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
line 311, in _adapter_disconnect
    self._check_state_on_disconnect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
line 141, in _check_state_on_disconnect
    raise exceptions.ProbableAuthenticationError
pika.exceptions.ProbableAuthenticationError

=================================================
Here is the log info:
=INFO REPORT==== 16-Sep-2013::22:27:29 ===
accepting AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572 -&gt; 127.0.0.1:5672)

=ERROR REPORT==== 16-Sep-2013::22:27:32 ===
closing AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572 -&gt; 127.0.0.1:5672):
{handshake_error,starting,0,
    {error,badarg,'connection.start_ok',
        [{rabbit_framing_amqp_0_9_1,encode_method_fields,1,[]},
         {rabbit_binary_generator,build_simple_method_frame,3,[]},
         {rabbit_writer,internal_send_command,4,[]},
         {rabbit_reader,send_on_channel0,3,[]},
         {rabbit_reader,auth_phase,2,[]},
         {rabbit_reader,handle_method0,3,[]},
         {rabbit_reader,handle_input,3,[]},
         {rabbit_reader,recvloop,2,[]}]}}

=================================================
*Anyone can tell me what's the problem?*
-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130916/7d6be839/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130916/7d6be839/attachment.htm</A>&gt;
</PRE>














<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="030227.html">[rabbitmq-discuss] Mobile Client Request [	iOS/Android/HTML5/etc...]
</A></li>
	<LI>Next message: <A HREF="030184.html">[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30183">[ date ]</a>
              <a href="thread.html#30183">[ thread ]</a>
              <a href="subject.html#30183">[ subject ]</a>
              <a href="author.html#30183">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
