<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%20pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3C6f707c0b-bb68-4370-9db0-d72942055c73%40googlegroups.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="030183.html">
   <LINK REL="Next"  HREF="030188.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError</H1>
    <B>&#38816;&#22823;&#21319;</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20can%20not%20connect%20to%20rabbitmq%20because%0A%20pika.exceptions.ProbableAuthenticationError&In-Reply-To=%3C6f707c0b-bb68-4370-9db0-d72942055c73%40googlegroups.com%3E"
       TITLE="[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError">dashengju at gmail.com
       </A><BR>
    <I>Mon Sep 16 16:10:15 BST 2013</I>
    <P><UL>
        <LI>Previous message: <A HREF="030183.html">[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
</A></li>
        <LI>Next message: <A HREF="030188.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30184">[ date ]</a>
              <a href="thread.html#30184">[ thread ]</a>
              <a href="subject.html#30184">[ subject ]</a>
              <a href="author.html#30184">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>when I change pika to 0.9.8, the error info change to :

No handlers could be found for logger &quot;pika.adapters.base_connection&quot;
Traceback (most recent call last):
  File &quot;./send.py&quot;, line 5, in &lt;module&gt;
    host='localhost'))
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;, 
line 61, in __init__
    super(BaseConnection, self).__init__(parameters, on_open_callback)
  File &quot;/usr/local/lib/python2.7/dist-packages/pika/connection.py&quot;, line 
513, in __init__
    self._connect()
  File &quot;/usr/local/lib/python2.7/dist-packages/pika/connection.py&quot;, line 
804, in _connect
    self._adapter_connect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;, 
line 146, in _adapter_connect
    self.process_data_events()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;, 
line 88, in process_data_events
    if self._handle_read():
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;, 
line 184, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;, 
line 300, in _handle_read
    return self._handle_error(error)
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py&quot;, 
line 264, in _handle_error
    self._handle_disconnect()
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;, 
line 181, in _handle_disconnect
    self._on_connection_closed(None, True)
  File 
&quot;/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py&quot;, 
line 235, in _on_connection_closed
    raise exceptions.AMQPConnectionError(*self.closing)
pika.exceptions.AMQPConnectionError: (0, '')

&#22312; 2013&#24180;9&#26376;16&#26085;&#26143;&#26399;&#19968;UTC+8&#19979;&#21320;11&#26102;04&#20998;35&#31186;&#65292;&#38816;&#22823;&#21319;&#20889;&#36947;&#65306;
&gt;<i>
</I>&gt;<i> hi, all
</I>&gt;<i>
</I>&gt;<i> I am newer to rabbitmq.
</I>&gt;<i>
</I>&gt;<i> I install a rabbitmq, just download, setup and startup the server. then I 
</I>&gt;<i> use a simple python client to connect, but the client report a error.
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is my version config:
</I>&gt;<i> python: 2.7
</I>&gt;<i> rabbitmq:  rabbitmq-server-generic-unix-3.1.5.tar.gz
</I>&gt;<i> erlang: otp_src_R16B01
</I>&gt;<i> pika: master
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is my python client:
</I>&gt;<i> #!/usr/bin/env python
</I>&gt;<i> import pika
</I>&gt;<i>
</I>&gt;<i> connection = pika.BlockingConnection(pika.ConnectionParameters(
</I>&gt;<i>             host='localhost'))
</I>&gt;<i> channel = connection.channel()
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> channel.queue_declare(queue='hello')
</I>&gt;<i>
</I>&gt;<i> channel.basic_publish(exchange='',
</I>&gt;<i>             routing_key='hello',
</I>&gt;<i>             body='Hello World!')
</I>&gt;<i> print &quot; [x] Sent 'Hello World!'&quot;
</I>&gt;<i> connection.close()
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is the error info:
</I>&gt;<i> Traceback (most recent call last):
</I>&gt;<i>   File &quot;send.py&quot;, line 5, in &lt;module&gt;
</I>&gt;<i>     host='localhost'))
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 123, in __init__
</I>&gt;<i>     super(BlockingConnection, self).__init__(parameters, None, False)
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
</I>&gt;<i> line 62, in __init__
</I>&gt;<i>     on_close_callback)
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/connection.py&quot;, 
</I>&gt;<i> line 593, in __init__
</I>&gt;<i>     self.connect()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 223, in connect
</I>&gt;<i>     error = self._adapter_connect()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 302, in _adapter_connect
</I>&gt;<i>     self.process_data_events()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 233, in process_data_events
</I>&gt;<i>     if self._handle_read():
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 346, in _handle_read
</I>&gt;<i>     super(BlockingConnection, self)._handle_read()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
</I>&gt;<i> line 323, in _handle_read
</I>&gt;<i>     return self._handle_error(error)
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
</I>&gt;<i> line 287, in _handle_error
</I>&gt;<i>     self._handle_disconnect()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 336, in _handle_disconnect
</I>&gt;<i>     self._adapter_disconnect()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/blocking_connection.py&quot;, 
</I>&gt;<i> line 311, in _adapter_disconnect
</I>&gt;<i>     self._check_state_on_disconnect()
</I>&gt;<i>   File 
</I>&gt;<i> &quot;/usr/local/lib/python2.7/dist-packages/pika-0.9.14p0-py2.7.egg/pika/adapters/base_connection.py&quot;, 
</I>&gt;<i> line 141, in _check_state_on_disconnect
</I>&gt;<i>     raise exceptions.ProbableAuthenticationError
</I>&gt;<i> pika.exceptions.ProbableAuthenticationError
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> Here is the log info:
</I>&gt;<i> =INFO REPORT==== 16-Sep-2013::22:27:29 ===
</I>&gt;<i> accepting AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572 -&gt; 127.0.0.1:5672)
</I>&gt;<i>
</I>&gt;<i> =ERROR REPORT==== 16-Sep-2013::22:27:32 ===
</I>&gt;<i> closing AMQP connection &lt;0.322.0&gt; (127.0.0.1:44572 -&gt; 127.0.0.1:5672):
</I>&gt;<i> {handshake_error,starting,0,
</I>&gt;<i>     {error,badarg,'connection.start_ok',
</I>&gt;<i>         [{rabbit_framing_amqp_0_9_1,encode_method_fields,1,[]},
</I>&gt;<i>          {rabbit_binary_generator,build_simple_method_frame,3,[]},
</I>&gt;<i>          {rabbit_writer,internal_send_command,4,[]},
</I>&gt;<i>          {rabbit_reader,send_on_channel0,3,[]},
</I>&gt;<i>          {rabbit_reader,auth_phase,2,[]},
</I>&gt;<i>          {rabbit_reader,handle_method0,3,[]},
</I>&gt;<i>          {rabbit_reader,handle_input,3,[]},
</I>&gt;<i>          {rabbit_reader,recvloop,2,[]}]}}
</I>&gt;<i>
</I>&gt;<i> =================================================
</I>&gt;<i> *Anyone can tell me what's the problem?*
</I>&gt;<i>
</I>-------------- next part --------------
An HTML attachment was scrubbed...
URL: &lt;<A HREF="http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130916/602ad7ef/attachment.htm">http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/attachments/20130916/602ad7ef/attachment.htm</A>&gt;
</PRE>















<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="030183.html">[rabbitmq-discuss] can not connect to rabbitmq because pika.exceptions.ProbableAuthenticationError
</A></li>
	<LI>Next message: <A HREF="030188.html">[rabbitmq-discuss] can not connect to rabbitmq because	pika.exceptions.ProbableAuthenticationError
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#30184">[ date ]</a>
              <a href="thread.html#30184">[ thread ]</a>
              <a href="subject.html#30184">[ subject ]</a>
              <a href="author.html#30184">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
