<tt>
&lt;div&nbsp;dir=&quot;ltr&quot;&gt;&lt;div&gt;I&nbsp;am&nbsp;testing&nbsp;failover&nbsp;before&nbsp;putting&nbsp;my&nbsp;RabbitMQ&nbsp;implementation&nbsp;into&nbsp;production.&nbsp;When&nbsp;I&nbsp;bring&nbsp;down&nbsp;one&nbsp;RabbitMQ&nbsp;node&nbsp;I&nbsp;start&nbsp;getting&nbsp;the&nbsp;following&nbsp;error:&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;div&gt;RabbitMQ.Client.Exceptions.OperationInterruptedException:&nbsp;The&nbsp;AMQP&nbsp;operation&nbsp;was&nbsp;interrupted:&nbsp;AMQP&nbsp;close-reason,&nbsp;initiated&nbsp;by&nbsp;Peer,&nbsp;code=404,&nbsp;text=&quot;NOT_FOUND&nbsp;-&nbsp;home&nbsp;node&nbsp;'rabbit@DEVRABBIT01'&nbsp;of&nbsp;durable&nbsp;queue&nbsp;'QUEUE_TEST'&nbsp;in&nbsp;vhost&nbsp;'/'&nbsp;is&nbsp;down&nbsp;or&nbsp;inaccessible&quot;,&nbsp;classId=50,&nbsp;methodId=10,&nbsp;cause=&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;I&nbsp;am&nbsp;running&nbsp;RabbitMQ&nbsp;3.2.2&nbsp;with&nbsp;Erlang&nbsp;R16B03.&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;DEVRABBIT01&nbsp;is&nbsp;the&nbsp;node&nbsp;that&nbsp;has&nbsp;been&nbsp;shut&nbsp;down.&nbsp;&lt;/div&gt;&lt;div&gt;DEVRABBIT02&nbsp;is&nbsp;the&nbsp;node&nbsp;that&nbsp;is&nbsp;still&nbsp;running&nbsp;and&nbsp;that&nbsp;the&nbsp;client&nbsp;is&nbsp;connected&nbsp;to.&lt;br&gt;&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;Both&nbsp;are&nbsp;disc&nbsp;nodes.&nbsp;The&nbsp;named&nbsp;queue&nbsp;(QUEUE_TEST)&nbsp;does&nbsp;not&nbsp;appear&nbsp;in&nbsp;the&nbsp;management&nbsp;console&nbsp;on&nbsp;the&nbsp;running&nbsp;node.&lt;/div&gt;&lt;div&gt;&lt;br&gt;&lt;/div&gt;&lt;div&gt;It&nbsp;looks&nbsp;like&nbsp;this&nbsp;was&nbsp;supposed&nbsp;to&nbsp;have&nbsp;been&nbsp;fixed&nbsp;in&nbsp;2.4.0.&nbsp;Any&nbsp;reason&nbsp;I&nbsp;would&nbsp;be&nbsp;seeing&nbsp;this&nbsp;in&nbsp;3.2.2?&lt;/div&gt;&lt;/div&gt;
</tt>
