<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 <HEAD>
   <TITLE> [rabbitmq-discuss] Fault-tolerant subscriptions using the .NET client
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Fault-tolerant%20subscriptions%20using%20the%20.NET%0A%20client&In-Reply-To=%3C4D91E682.2060306%40rabbitmq.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="012057.html">
   <LINK REL="Next"  HREF="012029.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[rabbitmq-discuss] Fault-tolerant subscriptions using the .NET client</H1>
    <B>Emile Joubert</B> 
    <A HREF="mailto:rabbitmq-discuss%40lists.rabbitmq.com?Subject=Re%3A%20%5Brabbitmq-discuss%5D%20Fault-tolerant%20subscriptions%20using%20the%20.NET%0A%20client&In-Reply-To=%3C4D91E682.2060306%40rabbitmq.com%3E"
       TITLE="[rabbitmq-discuss] Fault-tolerant subscriptions using the .NET client">emile at rabbitmq.com
       </A><BR>
    <I>Tue Mar 29 15:02:42 BST 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="012057.html">[rabbitmq-discuss] Fault-tolerant subscriptions using the .NET	client
</A></li>
        <LI>Next message: <A HREF="012029.html">[rabbitmq-discuss] rabbitmq-auth-backend-http
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#12109">[ date ]</a>
              <a href="thread.html#12109">[ thread ]</a>
              <a href="subject.html#12109">[ subject ]</a>
              <a href="author.html#12109">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi OJ,

On 25/03/11 20:35, OJ Reeves wrote:

&gt;<i> I am surprised to hear that the Dispose() method is called when the
</I>&gt;<i> connection is broken yet subsequent calls to subscription.Next()
</I>&gt;<i> continue to function and return 'true'. This seems a little
</I>&gt;<i> counter-intuitive to me. I would expect that attempting to called Next()
</I>&gt;<i> on a subscription that has been disposed would result in some kind of error.
</I>
That's not what I see. As soon as a connection error occurs, the 
subscription is disposed and calls to Next() return null. Perhaps 
Dispose() is not getting called in your case. One possible reason for 
that is an incorrectly trapped exception.

Regards

Emile
</PRE>





<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="012057.html">[rabbitmq-discuss] Fault-tolerant subscriptions using the .NET	client
</A></li>
	<LI>Next message: <A HREF="012029.html">[rabbitmq-discuss] rabbitmq-auth-backend-http
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#12109">[ date ]</a>
              <a href="thread.html#12109">[ thread ]</a>
              <a href="subject.html#12109">[ subject ]</a>
              <a href="author.html#12109">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.rabbitmq.com/cgi-bin/mailman/listinfo/rabbitmq-discuss">More information about the rabbitmq-discuss
mailing list</a><br>
</body></html>
