<tt>
Hi,&nbsp;&lt;br&gt;&lt;br&gt;I&amp;#39;m&nbsp;testing&nbsp;rabbitmq&nbsp;pubsub&nbsp;pattern&nbsp;with&nbsp;pika&nbsp;0.9.5.&nbsp;Basically&nbsp;what&nbsp;I&nbsp;do&nbsp;are&nbsp;the&nbsp;following:&nbsp;&lt;br&gt;&lt;br&gt;1.&nbsp;publish&nbsp;message&nbsp;in&nbsp;a&nbsp;tornado&nbsp;application&lt;br&gt;2.&nbsp;consume&nbsp;message&nbsp;in&nbsp;a&nbsp;standalone&nbsp;script&lt;br&gt;3.&nbsp;ab&nbsp;test&nbsp;the&nbsp;tornado&nbsp;application&nbsp;to&nbsp;see&nbsp;how&nbsp;messages&nbsp;goes&lt;br&gt;<br>
&lt;br&gt;basic&nbsp;parameters&nbsp;used:&lt;br&gt;&lt;br&gt;1.&nbsp;exchange_type&nbsp;=&nbsp;fanout&lt;br&gt;2.&nbsp;auto_delete&nbsp;=&nbsp;False&lt;br&gt;3.&nbsp;durable&nbsp;=&nbsp;True&lt;br&gt;4.&nbsp;delivery_mode&nbsp;=&nbsp;2&lt;br&gt;5.&nbsp;no_ack&nbsp;=&nbsp;True&lt;br&gt;6.&nbsp;SimpleReconnectionStrategy&nbsp;for&nbsp;reconnection&lt;br&gt;&lt;br&gt;When&nbsp;I&amp;#39;m&nbsp;testing&nbsp;the&nbsp;server&nbsp;die&nbsp;scenario.&nbsp;I&nbsp;found&nbsp;three&nbsp;issues:&lt;br&gt;<br>
&lt;br&gt;ISSUE&nbsp;1:&lt;br&gt;=======&lt;br&gt;Stop&nbsp;rabbitmq&nbsp;server,&nbsp;tornado&nbsp;application&nbsp;raises&nbsp;the&nbsp;following&nbsp;exception&nbsp;and&nbsp;become&nbsp;not&nbsp;responsive:&lt;br&gt;&lt;br&gt;2011-04-23&nbsp;11:48:53,872&nbsp;-&nbsp;ERROR&nbsp;-&nbsp;TornadoConnection:&nbsp;Socket&nbsp;Error&nbsp;on&nbsp;9:&nbsp;104&lt;br&gt;2011-04-23&nbsp;11:48:53,872&nbsp;-&nbsp;ERROR&nbsp;-&nbsp;Exception&nbsp;in&nbsp;I/O&nbsp;handler&nbsp;for&nbsp;fd&nbsp;9&lt;br&gt;<br>
Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/ioloop.py&amp;quot;,&nbsp;line&nbsp;272,&nbsp;in&nbsp;start&lt;br&gt;   &nbsp;self._handlers[fd](fd,&nbsp;events)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/stack_context.py&amp;quot;,&nbsp;line&nbsp;128,&nbsp;in&nbsp;wrapped&lt;br&gt;<br>
   &nbsp;callback(*args,&nbsp;**kwargs)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/adapters/base_connection.py&amp;quot;,&nbsp;line&nbsp;137,&nbsp;in&nbsp;_handle_events&lt;br&gt;   &nbsp;self._handle_error(error)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/adapters/base_connection.py&amp;quot;,&nbsp;line&nbsp;106,&nbsp;in&nbsp;_handle_error&lt;br&gt;<br>
   &nbsp;error_code&nbsp;=&nbsp;error[0] &nbsp;#&nbsp;Python&nbsp;&amp;lt;=&nbsp;2.5&lt;br&gt;TypeError:&nbsp;&amp;#39;NoneType&amp;#39;&nbsp;object&nbsp;is&nbsp;unsubscriptable&lt;br&gt;2011-04-23&nbsp;11:48:53,886&nbsp;-&nbsp;ERROR&nbsp;-&nbsp;Exception&nbsp;in&nbsp;callback&nbsp;&amp;lt;functools.partial&nbsp;object&nbsp;at&nbsp;0x9e500f4&amp;gt;&lt;br&gt;Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):&lt;br&gt;<br>
 &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/ioloop.py&amp;quot;,&nbsp;line&nbsp;333,&nbsp;in&nbsp;_run_callback&lt;br&gt;   &nbsp;callback()&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/tornado-1.1-py2.6.egg/tornado/stack_context.py&amp;quot;,&nbsp;line&nbsp;128,&nbsp;in&nbsp;wrapped&lt;br&gt;<br>
   &nbsp;callback(*args,&nbsp;**kwargs)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/home/ken/workspace/QvodGround2/utils/messaging.py&amp;quot;,&nbsp;line&nbsp;53,&nbsp;in&nbsp;connect&lt;br&gt;   &nbsp;reconnection_strategy=srs)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/adapters/tornado_connection.py&amp;quot;,&nbsp;line&nbsp;33,&nbsp;in&nbsp;__init__&lt;br&gt;<br>
   &nbsp;reconnection_strategy)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/adapters/base_connection.py&amp;quot;,&nbsp;line&nbsp;50,&nbsp;in&nbsp;__init__&lt;br&gt;   &nbsp;reconnection_strategy)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/connection.py&amp;quot;,&nbsp;line&nbsp;170,&nbsp;in&nbsp;__init__&lt;br&gt;<br>
   &nbsp;self._connect()&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/connection.py&amp;quot;,&nbsp;line&nbsp;228,&nbsp;in&nbsp;_connect&lt;br&gt;   &nbsp;self.parameters.port&nbsp;or &nbsp;spec.PORT)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/adapters/tornado_connection.py&amp;quot;,&nbsp;line&nbsp;39,&nbsp;in&nbsp;_adapter_connect&lt;br&gt;<br>
   &nbsp;BaseConnection._adapter_connect(self,&nbsp;host,&nbsp;port)&lt;br&gt; &nbsp;File&nbsp;&amp;quot;/usr/local/lib/python2.6/dist-packages/pika-0.9.5-py2.6.egg/pika/adapters/base_connection.py&amp;quot;,&nbsp;line&nbsp;58,&nbsp;in&nbsp;_adapter_connect&lt;br&gt;   &nbsp;self.socket.connect((host,&nbsp;port))&lt;br&gt;<br>
 &nbsp;File&nbsp;&amp;quot;&amp;lt;string&amp;gt;&amp;quot;,&nbsp;line&nbsp;1,&nbsp;in&nbsp;connect&lt;br&gt;error:&nbsp;[Errno&nbsp;111]&nbsp;Connection&nbsp;refused&lt;br&gt;&lt;br&gt;ISSUE2:&lt;br&gt;=======&lt;br&gt;I&nbsp;tested&nbsp;800&nbsp;messages,&nbsp;with&nbsp;slow&nbsp;consumer.&nbsp;while&nbsp;it&nbsp;runs,&nbsp;stop&nbsp;rabbitmq-server&nbsp;with&nbsp;Ctrl+C,&nbsp;consumer&nbsp;is&nbsp;able&nbsp;to&nbsp;continuing&nbsp;consuming&nbsp;message&nbsp;and&nbsp;finish&nbsp;all&nbsp;800&nbsp;messages,&nbsp;then&nbsp;it&nbsp;EXIT.&lt;br&gt;<br>
&lt;br&gt;It&amp;#39;s&nbsp;very&nbsp;weird&nbsp;indeed,&nbsp;because&nbsp;the&nbsp;server&nbsp;already&nbsp;gone.&nbsp;Is&nbsp;there&nbsp;any&nbsp;incoming&nbsp;message&nbsp;buffer&nbsp;in&nbsp;pika?&nbsp;How&nbsp;many&nbsp;messages&nbsp;can&nbsp;be&nbsp;buffered?&nbsp;Are&nbsp;those&nbsp;message&nbsp;stored&nbsp;in&nbsp;memory?&nbsp;Is&nbsp;it&nbsp;possible&nbsp;to&nbsp;configure&nbsp;the&nbsp;memory&nbsp;usage?&lt;br&gt;<br>
&lt;br&gt;ISSUE3:&lt;br&gt;=======&lt;br&gt;In&nbsp;my&nbsp;use&nbsp;case,&nbsp;it&amp;#39;s&nbsp;very&nbsp;important&nbsp;the&nbsp;tornado&nbsp;application&nbsp;wouldn&amp;#39;t&nbsp;die&nbsp;for&nbsp;any&nbsp;reason.&nbsp;If&nbsp;there&nbsp;is&nbsp;anything&nbsp;bad&nbsp;happened&nbsp;to&nbsp;the&nbsp;rabbitmq-server&nbsp;or&nbsp;connection,&nbsp;messaging&nbsp;system&nbsp;can&nbsp;be&nbsp;down-graded&nbsp;as&nbsp;a&nbsp;not&nbsp;functioning&nbsp;part,&nbsp;which&nbsp;can&nbsp;go&nbsp;back&nbsp;automatically&nbsp;when&nbsp;server&nbsp;issues&nbsp;resolved.&nbsp;The&nbsp;long&nbsp;running&nbsp;consuming&nbsp;process&nbsp;shouldn&amp;#39;t&nbsp;die&nbsp;or&nbsp;exit&nbsp;when&nbsp;server&nbsp;died&nbsp;or&nbsp;connection&nbsp;broken.&nbsp;Is&nbsp;this&nbsp;requirement&nbsp;sensible&nbsp;enough?&nbsp;&lt;br&gt;<br>
&lt;br&gt;I&nbsp;hope&nbsp;SimpleReconnectionStrategy&nbsp;works&nbsp;for&nbsp;my&nbsp;case,&nbsp;which&nbsp;is&nbsp;not.&nbsp;Is&nbsp;there&nbsp;anything&nbsp;wrong&nbsp;in&nbsp;my&nbsp;application&nbsp;code?&nbsp;Or&nbsp;I&nbsp;just&nbsp;roll&nbsp;my&nbsp;own&nbsp;one,&nbsp;any&nbsp;suggestion&nbsp;on&nbsp;how&nbsp;to&nbsp;do&nbsp;it?&lt;br&gt;&lt;br&gt;I&nbsp;appreciate&nbsp;any&nbsp;help.&lt;br&gt;&lt;br&gt;Best&nbsp;regards!&lt;br&gt;<br>
can&lt;br&gt;&lt;br&gt;PS: &nbsp;partial&nbsp;tornado&nbsp;application&nbsp;code&nbsp;can&nbsp;be&nbsp;found&nbsp;at&nbsp;gist:&nbsp;&lt;a&nbsp;href=&quot;https://gist.github.com/938517&quot;&gt;https://gist.github.com/938517&lt;/a&gt;&nbsp;,&nbsp;consumer&nbsp;script:&nbsp;&lt;a&nbsp;href=&quot;https://gist.github.com/938226&quot;&gt;https://gist.github.com/938226&lt;/a&gt;&lt;br&gt;<br>
&lt;br&gt;<br>

</tt>
